# Task: напиши hello world на python
# Generated by Coder Team

def main() -> None:
    """
    Main function to print "Hello, World" and handle any exceptions.
    """
    try:
        print("Hello, World")
    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    main()
